//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UserInterface.RogersWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Rogers_APISoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Person))]
    public partial class Rogers_API : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback searchClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback addClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateBasicDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback addEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchOrderStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback addproductOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback addOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Rogers_API() {
            this.Url = global::UserInterface.Properties.Settings.Default.UserInterface_RogersWS_Rogers_API;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchClientsCompletedEventHandler searchClientsCompleted;
        
        /// <remarks/>
        public event addClientCompletedEventHandler addClientCompleted;
        
        /// <remarks/>
        public event updateBasicDataCompletedEventHandler updateBasicDataCompleted;
        
        /// <remarks/>
        public event changeStateCompletedEventHandler changeStateCompleted;
        
        /// <remarks/>
        public event deleteEmployeeCompletedEventHandler deleteEmployeeCompleted;
        
        /// <remarks/>
        public event updateEmployeeCompletedEventHandler updateEmployeeCompleted;
        
        /// <remarks/>
        public event searchEmployeeCompletedEventHandler searchEmployeeCompleted;
        
        /// <remarks/>
        public event addEmployeeCompletedEventHandler addEmployeeCompleted;
        
        /// <remarks/>
        public event searchOrderStatesCompletedEventHandler searchOrderStatesCompleted;
        
        /// <remarks/>
        public event setTimeCompletedEventHandler setTimeCompleted;
        
        /// <remarks/>
        public event addproductCompletedEventHandler addproductCompleted;
        
        /// <remarks/>
        public event deleteProductCompletedEventHandler deleteProductCompleted;
        
        /// <remarks/>
        public event searchProductCompletedEventHandler searchProductCompleted;
        
        /// <remarks/>
        public event updateProductCompletedEventHandler updateProductCompleted;
        
        /// <remarks/>
        public event addOrderCompletedEventHandler addOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchClients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string searchClients(string param) {
            object[] results = this.Invoke("searchClients", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void searchClientsAsync(string param) {
            this.searchClientsAsync(param, null);
        }
        
        /// <remarks/>
        public void searchClientsAsync(string param, object userState) {
            if ((this.searchClientsOperationCompleted == null)) {
                this.searchClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchClientsOperationCompleted);
            }
            this.InvokeAsync("searchClients", new object[] {
                        param}, this.searchClientsOperationCompleted, userState);
        }
        
        private void OnsearchClientsOperationCompleted(object arg) {
            if ((this.searchClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchClientsCompleted(this, new searchClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addClient(string fullname, string password, string profilepictureurl, string email, string address) {
            this.Invoke("addClient", new object[] {
                        fullname,
                        password,
                        profilepictureurl,
                        email,
                        address});
        }
        
        /// <remarks/>
        public void addClientAsync(string fullname, string password, string profilepictureurl, string email, string address) {
            this.addClientAsync(fullname, password, profilepictureurl, email, address, null);
        }
        
        /// <remarks/>
        public void addClientAsync(string fullname, string password, string profilepictureurl, string email, string address, object userState) {
            if ((this.addClientOperationCompleted == null)) {
                this.addClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddClientOperationCompleted);
            }
            this.InvokeAsync("addClient", new object[] {
                        fullname,
                        password,
                        profilepictureurl,
                        email,
                        address}, this.addClientOperationCompleted, userState);
        }
        
        private void OnaddClientOperationCompleted(object arg) {
            if ((this.addClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addClientCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateBasicData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateBasicData(string fullname, string address, string password, string email) {
            object[] results = this.Invoke("updateBasicData", new object[] {
                        fullname,
                        address,
                        password,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateBasicDataAsync(string fullname, string address, string password, string email) {
            this.updateBasicDataAsync(fullname, address, password, email, null);
        }
        
        /// <remarks/>
        public void updateBasicDataAsync(string fullname, string address, string password, string email, object userState) {
            if ((this.updateBasicDataOperationCompleted == null)) {
                this.updateBasicDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateBasicDataOperationCompleted);
            }
            this.InvokeAsync("updateBasicData", new object[] {
                        fullname,
                        address,
                        password,
                        email}, this.updateBasicDataOperationCompleted, userState);
        }
        
        private void OnupdateBasicDataOperationCompleted(object arg) {
            if ((this.updateBasicDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateBasicDataCompleted(this, new updateBasicDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/changeState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool changeState(bool state, string email) {
            object[] results = this.Invoke("changeState", new object[] {
                        state,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void changeStateAsync(bool state, string email) {
            this.changeStateAsync(state, email, null);
        }
        
        /// <remarks/>
        public void changeStateAsync(bool state, string email, object userState) {
            if ((this.changeStateOperationCompleted == null)) {
                this.changeStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeStateOperationCompleted);
            }
            this.InvokeAsync("changeState", new object[] {
                        state,
                        email}, this.changeStateOperationCompleted, userState);
        }
        
        private void OnchangeStateOperationCompleted(object arg) {
            if ((this.changeStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeStateCompleted(this, new changeStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteEmployee(string username) {
            object[] results = this.Invoke("deleteEmployee", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string username) {
            this.deleteEmployeeAsync(username, null);
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string username, object userState) {
            if ((this.deleteEmployeeOperationCompleted == null)) {
                this.deleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteEmployeeOperationCompleted);
            }
            this.InvokeAsync("deleteEmployee", new object[] {
                        username}, this.deleteEmployeeOperationCompleted, userState);
        }
        
        private void OndeleteEmployeeOperationCompleted(object arg) {
            if ((this.deleteEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteEmployeeCompleted(this, new deleteEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateEmployee(string fullname, string password, string username, bool isadmin) {
            object[] results = this.Invoke("updateEmployee", new object[] {
                        fullname,
                        password,
                        username,
                        isadmin});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string fullname, string password, string username, bool isadmin) {
            this.updateEmployeeAsync(fullname, password, username, isadmin, null);
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string fullname, string password, string username, bool isadmin, object userState) {
            if ((this.updateEmployeeOperationCompleted == null)) {
                this.updateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("updateEmployee", new object[] {
                        fullname,
                        password,
                        username,
                        isadmin}, this.updateEmployeeOperationCompleted, userState);
        }
        
        private void OnupdateEmployeeOperationCompleted(object arg) {
            if ((this.updateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateEmployeeCompleted(this, new updateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee[] searchEmployee(string filter) {
            object[] results = this.Invoke("searchEmployee", new object[] {
                        filter});
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void searchEmployeeAsync(string filter) {
            this.searchEmployeeAsync(filter, null);
        }
        
        /// <remarks/>
        public void searchEmployeeAsync(string filter, object userState) {
            if ((this.searchEmployeeOperationCompleted == null)) {
                this.searchEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchEmployeeOperationCompleted);
            }
            this.InvokeAsync("searchEmployee", new object[] {
                        filter}, this.searchEmployeeOperationCompleted, userState);
        }
        
        private void OnsearchEmployeeOperationCompleted(object arg) {
            if ((this.searchEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchEmployeeCompleted(this, new searchEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addEmployee(string fullname, string password, string username, bool isadmin) {
            object[] results = this.Invoke("addEmployee", new object[] {
                        fullname,
                        password,
                        username,
                        isadmin});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addEmployeeAsync(string fullname, string password, string username, bool isadmin) {
            this.addEmployeeAsync(fullname, password, username, isadmin, null);
        }
        
        /// <remarks/>
        public void addEmployeeAsync(string fullname, string password, string username, bool isadmin, object userState) {
            if ((this.addEmployeeOperationCompleted == null)) {
                this.addEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddEmployeeOperationCompleted);
            }
            this.InvokeAsync("addEmployee", new object[] {
                        fullname,
                        password,
                        username,
                        isadmin}, this.addEmployeeOperationCompleted, userState);
        }
        
        private void OnaddEmployeeOperationCompleted(object arg) {
            if ((this.addEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addEmployeeCompleted(this, new addEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchOrderStates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderState[] searchOrderStates() {
            object[] results = this.Invoke("searchOrderStates", new object[0]);
            return ((OrderState[])(results[0]));
        }
        
        /// <remarks/>
        public void searchOrderStatesAsync() {
            this.searchOrderStatesAsync(null);
        }
        
        /// <remarks/>
        public void searchOrderStatesAsync(object userState) {
            if ((this.searchOrderStatesOperationCompleted == null)) {
                this.searchOrderStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchOrderStatesOperationCompleted);
            }
            this.InvokeAsync("searchOrderStates", new object[0], this.searchOrderStatesOperationCompleted, userState);
        }
        
        private void OnsearchOrderStatesOperationCompleted(object arg) {
            if ((this.searchOrderStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchOrderStatesCompleted(this, new searchOrderStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setTime(int id, System.DateTime time) {
            object[] results = this.Invoke("setTime", new object[] {
                        id,
                        time});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setTimeAsync(int id, System.DateTime time) {
            this.setTimeAsync(id, time, null);
        }
        
        /// <remarks/>
        public void setTimeAsync(int id, System.DateTime time, object userState) {
            if ((this.setTimeOperationCompleted == null)) {
                this.setTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTimeOperationCompleted);
            }
            this.InvokeAsync("setTime", new object[] {
                        id,
                        time}, this.setTimeOperationCompleted, userState);
        }
        
        private void OnsetTimeOperationCompleted(object arg) {
            if ((this.setTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTimeCompleted(this, new setTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addproduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addproduct(string productname, string description, double price, string image, bool isoutofstoc, int category) {
            object[] results = this.Invoke("addproduct", new object[] {
                        productname,
                        description,
                        price,
                        image,
                        isoutofstoc,
                        category});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addproductAsync(string productname, string description, double price, string image, bool isoutofstoc, int category) {
            this.addproductAsync(productname, description, price, image, isoutofstoc, category, null);
        }
        
        /// <remarks/>
        public void addproductAsync(string productname, string description, double price, string image, bool isoutofstoc, int category, object userState) {
            if ((this.addproductOperationCompleted == null)) {
                this.addproductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddproductOperationCompleted);
            }
            this.InvokeAsync("addproduct", new object[] {
                        productname,
                        description,
                        price,
                        image,
                        isoutofstoc,
                        category}, this.addproductOperationCompleted, userState);
        }
        
        private void OnaddproductOperationCompleted(object arg) {
            if ((this.addproductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addproductCompleted(this, new addproductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteProduct(int id) {
            object[] results = this.Invoke("deleteProduct", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteProductAsync(int id) {
            this.deleteProductAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteProductAsync(int id, object userState) {
            if ((this.deleteProductOperationCompleted == null)) {
                this.deleteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteProductOperationCompleted);
            }
            this.InvokeAsync("deleteProduct", new object[] {
                        id}, this.deleteProductOperationCompleted, userState);
        }
        
        private void OndeleteProductOperationCompleted(object arg) {
            if ((this.deleteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteProductCompleted(this, new deleteProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] searchProduct(string productname) {
            object[] results = this.Invoke("searchProduct", new object[] {
                        productname});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void searchProductAsync(string productname) {
            this.searchProductAsync(productname, null);
        }
        
        /// <remarks/>
        public void searchProductAsync(string productname, object userState) {
            if ((this.searchProductOperationCompleted == null)) {
                this.searchProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchProductOperationCompleted);
            }
            this.InvokeAsync("searchProduct", new object[] {
                        productname}, this.searchProductOperationCompleted, userState);
        }
        
        private void OnsearchProductOperationCompleted(object arg) {
            if ((this.searchProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchProductCompleted(this, new searchProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateProduct(int id, string name, string descr, double price, string imageuri, int stock, int cat) {
            object[] results = this.Invoke("updateProduct", new object[] {
                        id,
                        name,
                        descr,
                        price,
                        imageuri,
                        stock,
                        cat});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateProductAsync(int id, string name, string descr, double price, string imageuri, int stock, int cat) {
            this.updateProductAsync(id, name, descr, price, imageuri, stock, cat, null);
        }
        
        /// <remarks/>
        public void updateProductAsync(int id, string name, string descr, double price, string imageuri, int stock, int cat, object userState) {
            if ((this.updateProductOperationCompleted == null)) {
                this.updateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateProductOperationCompleted);
            }
            this.InvokeAsync("updateProduct", new object[] {
                        id,
                        name,
                        descr,
                        price,
                        imageuri,
                        stock,
                        cat}, this.updateProductOperationCompleted, userState);
        }
        
        private void OnupdateProductOperationCompleted(object arg) {
            if ((this.updateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateProductCompleted(this, new updateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addOrder(int id, Product[] prods) {
            object[] results = this.Invoke("addOrder", new object[] {
                        id,
                        prods});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addOrderAsync(int id, Product[] prods) {
            this.addOrderAsync(id, prods, null);
        }
        
        /// <remarks/>
        public void addOrderAsync(int id, Product[] prods, object userState) {
            if ((this.addOrderOperationCompleted == null)) {
                this.addOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddOrderOperationCompleted);
            }
            this.InvokeAsync("addOrder", new object[] {
                        id,
                        prods}, this.addOrderOperationCompleted, userState);
        }
        
        private void OnaddOrderOperationCompleted(object arg) {
            if ((this.addOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addOrderCompleted(this, new addOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : Person {
        
        private string uSERNAMEField;
        
        private bool isADMINField;
        
        /// <remarks/>
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public bool isADMIN {
            get {
                return this.isADMINField;
            }
            set {
                this.isADMINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Person {
        
        private int pERSON_IDField;
        
        private string fULLNAMEField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        public int PERSON_ID {
            get {
                return this.pERSON_IDField;
            }
            set {
                this.pERSON_IDField = value;
            }
        }
        
        /// <remarks/>
        public string FULLNAME {
            get {
                return this.fULLNAMEField;
            }
            set {
                this.fULLNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Product {
        
        private int pRODUCT_IDField;
        
        private string pRODUCTNAMEField;
        
        private string dESCRIPTIONField;
        
        private double pRICEField;
        
        private string iMAGEURIField;
        
        private bool isoutofstockField;
        
        private int categoryField;
        
        /// <remarks/>
        public int PRODUCT_ID {
            get {
                return this.pRODUCT_IDField;
            }
            set {
                this.pRODUCT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public double PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        public string IMAGEURI {
            get {
                return this.iMAGEURIField;
            }
            set {
                this.iMAGEURIField = value;
            }
        }
        
        /// <remarks/>
        public bool isoutofstock {
            get {
                return this.isoutofstockField;
            }
            set {
                this.isoutofstockField = value;
            }
        }
        
        /// <remarks/>
        public int category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderState {
        
        private string nAMEField;
        
        private System.DateTime tIMEASIGNEDField;
        
        private int orderStateIDField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TIMEASIGNED {
            get {
                return this.tIMEASIGNEDField;
            }
            set {
                this.tIMEASIGNEDField = value;
            }
        }
        
        /// <remarks/>
        public int orderStateID {
            get {
                return this.orderStateIDField;
            }
            set {
                this.orderStateIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void searchClientsCompletedEventHandler(object sender, searchClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void addClientCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void updateBasicDataCompletedEventHandler(object sender, updateBasicDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateBasicDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateBasicDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void changeStateCompletedEventHandler(object sender, changeStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deleteEmployeeCompletedEventHandler(object sender, deleteEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void updateEmployeeCompletedEventHandler(object sender, updateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void searchEmployeeCompletedEventHandler(object sender, searchEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void addEmployeeCompletedEventHandler(object sender, addEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void searchOrderStatesCompletedEventHandler(object sender, searchOrderStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchOrderStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchOrderStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderState[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderState[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void setTimeCompletedEventHandler(object sender, setTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void addproductCompletedEventHandler(object sender, addproductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addproductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addproductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deleteProductCompletedEventHandler(object sender, deleteProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void searchProductCompletedEventHandler(object sender, searchProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void updateProductCompletedEventHandler(object sender, updateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void addOrderCompletedEventHandler(object sender, addOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591